### ISSUE TITLE
Meeting: October 25th, North Vancouver, Django 

### ISSUE THREAD

**Issue by andymckay** [vancouver/vanpy#12]
We've got a new meeting coming up 🎉😎

## When

Wednesday, October 25th, 6:30pm

## Where

Jane
500 - 138 13th Street East, North Vancouver, British Columbia, Canada V7L 0E5
See: 👉🏾 https://github.com/vancouver/vanpy/issues/11

## Talks

A perspective on Django from an old timer
See: 👉🏾 https://github.com/vancouver/vanpy/issues/8

@mariatta will be talking about PyCon US for a few minutes 🥳 

... and if there's anything else anyone wants to talk about, please [file an issue](https://github.com/vancouver/vanpy/issues/new?assignees=&labels=Talk+Proposal&projects=&template=talk-proposal.md&title=Talk+proposal%3A+), comment below, or just drop me a line.

## Standard info
* Everyone who comes should follow the [code of conduct](https://github.com/vancouver/vanpy/blob/master/code_of_conduct.md), which we will enforce. Be nice to each other and make a space we can all visit.
* We'll try to make every meeting a hybrid one, so people can can join remotely. We do understand that not everyone is comfortable turning up to a room full of people.
* If there is a room limit, we'll come up with a system to figure that out.
* Recording the meeting isn't something we plan on doing just yet.
* We encourage speakers to share their slides and demos later on if possible, but its up to the speakers.

That's it, we hope you can join us and come hang out with fellow Python people.

**Comment by nth10sd** [comment]
Hi @andymckay, I'd like to propose a talk titled "How to use Rust with Python" for this date.

A caveat is, I'm flying back and scheduled to land in the city a couple of hours prior. If I'm delayed in any way, I won't be able to make it in person and so will have to push it off to the next one.

I've tried to reach out on LinkedIn as well.

**Comment by andymckay** [comment]
Hey @nth10sd 👋🏾 awesome thanks for the suggestion. That's totally fine, if you aren't able to make it, we'll push it back to the next one. How long do you think your talk would be?

**Comment by nth10sd** [comment]
Probably around 45 minutes! Thanks for connecting on LI as well.

**Comment by andymckay** [comment]
Fantastic. I think we should do that talk in November - we don't have a speaker yet so it would good to have one lined up in advance.

I've also generally strived not to make the talks to long and together we'd be well over an hour or more. Add in socializing and a round table etc and it gets to be a long event.

Would a November talk time work for you?

**Comment by nth10sd** [comment]
Sure, I won't rush over for the October one then if it's not necessary.

If it's the November one, I'm not in town from Nov 20th onwards. What date is that exactly?

**Comment by andymckay** [comment]
Let's do it before Nov 20th 😀 haven't decided a date yet. Would you mind creating an issue for your talk?

**Comment by nth10sd** [comment]
Done, #13 !

**Comment by L2iexpert** [comment]
I'm actually remote. I'm based in Dallas and was hoping you would have virtual meetings.

I'd also like to find someone who would be willing to consult and mentor on inline forms and Crispy. We have a few years of class-based forms but this is new to us.

Lamont@IntegrationExpert.com
214-454-4144

**Comment by andymckay** [comment]
An update that @mariatta will be coming and speaking as well about PyCon US 🥳 you are all coming right?

**Comment by nth10sd** [comment]
I popped by at around 7pm having rushed over as soon as I could, to try to join in near the end, but I couldn't find a way up from the lobby, I'm sorry.

**Comment by andymckay** [comment]
Oh no! I'm sending someone down.

**Comment by Mariatta** [comment]
Thanks so much for organizing the meetup!
Here are my slides from last night about PyCon US 2024
[PyCon US 2024 - VanPy.pdf](https://github.com/vancouver/vanpy/files/13180106/PyCon.US.2024.-.VanPy.pdf)

**Comment by Mariatta** [comment]
Here are the slides viewable on your browser: https://speakerdeck.com/mariatta/introduction-to-pycon-us-2024

**Comment by andymckay** [comment]
My presentation is [available here](https://docs.google.com/presentation/d/1MkSGIv3eLCnCfgSb_N29bHcSE5PEwAz62X4cFzaUXN0/edit#slide=id.g292061c0623_1_304). Thank you everyone for coming.

Here's a pic of the crowd: 
![IMG_5817](https://github.com/vancouver/vanpy/assets/74699/4bdcc60d-7dd5-4424-922e-755a5bcd28ea)

**Comment by Mariatta** [comment]
Can I post that on social media?

**Comment by andymckay** [comment]
Well I didn't explicitly say we'd put it there, I think I said just GitHub. But it's public here anyways...
