### ISSUE TITLE
Talk proposal: AI Testing Odyssey: From Foundations to Future Frontiers

### ISSUE THREAD

**Issue by jazzatjane** [vancouver/vanpy#20]
If you are using this form, a big thank you from the organisers 🙇‍♀ talks really help pull people in.

Anyone is welcome to talk on any topic. In the past we've talks on a super wide range of topics and we'd welcome anyone, from those new to giving talks to those experience conference speakers. Talks can be from 5-45 mins long. I mean you could do longer if you want...

## About the talk
Please replace the following bits below 👇

* **Title**:  AI Testing Odyssey: From Foundations to Future Frontiers
* **Description**: Why we need to test AI, how testing of AI evolved with evolution of AI, the challenges encountered, the breakthroughs and the rise of responsible AI. Reimagining AI Testing in the era of Gen AI, latest challenges, advancements, tooling and the unsolved enigmas.
* **Duration (approx.)**: 45 mins + 10 minutes for Q/A

## What you as a talk proposer need to know

If you could just check these off so we know you've read them.
* [ ✔ ] Please ensure you've [read the code of conduct](https://github.com/vancouver/vanpy/blob/master/code_of_conduct.md)
* [ ✔ ] Don't say things that are confidential and will get your, company, or anyone in the audience in any legal trouble 🤑
* [ ✔ ] The person hosting the space will provide Wifi and an a screen, we'll have people dialing in remotely. If there's anything else you need, you'll let us know right? 😀
* [ ✔ ] After the talk, posting slides and code and somewhere (even this repo) would be appreciated, but its not required.

## Additional context
* I can do the talk remotely starting 3rd week of Feb. But in-person talk will only be possible mid April onwards.

**Comment by nth10sd** [comment]
@andymckay Any thoughts?

**Comment by andymckay** [comment]
Thanks for the ping @nth10sd this got totally lost in my GitHub notifications.

Thanks @jazzatjane, that sounds great. I just want to check that there's a Python angle in there, beyond a general AI talk? Some of the words like tooling, sound like it might be Python related. Just want to check its relevant to the group.

If so, April sound awesome and we can tee you up.

**Comment by jazzatjane** [comment]
LLM implementation is happening using Python libraries, think LangChain, and tooling on LLM observability, evaluation of LLM's, guardrails for alignment of AI, versioning of prompts etc is all in python. In today's world, python developers are better AI engineers than people who studied Deep Learning, because modelling is replaced by prompting.

**Comment by andymckay** [comment]
Awesome, sounds great 🙇🏾  Give us a date in April, usually Tue-Thur works best and I'll see if the venue is available.

**Comment by andymckay** [comment]
Confirmed @jazzatjane 👍🏾  I'll put out announcement after the next meeting, still looking to see if I can find a talk for March 😄

**Comment by andymckay** [comment]
@jazzatjane still cool for next week?

**Comment by jazzatjane** [comment]
Absolutely, slides are WIP.

**Comment by andymckay** [comment]
All the best talks are a WIP till the last minute 😄
