### ISSUE TITLE
Talk proposal: Building (and hosting) your own simple blog with Python+Pelican (and HTML/CSS/JS)

### ISSUE THREAD

**Issue by kburts** [vancouver/vanpy#21]
## About the talk

* **Title**: Create your own simple Blog with Pelican
* **Description**: How (and a couple ideas as to why) you can create your own blog and share it with the world. A couple of other benefits associated with it having your own domain name and server too.
* **Duration (approx.)**: Probably ~45 mins.

## What you as a talk proposer need to know

If you could just check these off so we know you've read them.
* [x] Please ensure you've [read the code of conduct](https://github.com/vancouver/vanpy/blob/master/code_of_conduct.md)
* [x] Don't say things that are confidential and will get your, company, or anyone in the audience in any legal trouble 🤑
* [x] The person hosting the space will provide Wifi and an a screen, we'll have people dialing in remotely. If there's anything else you need, you'll let us know right? 😀
* [x] After the talk, posting slides and code and somewhere (even this repo) would be appreciated, but its not required.

## Additional context

I think it'd be really fun to do a code-along with deploying to GitHub Pages so that all participants end the day with their own actually hosted up and running blog that they can use from now on. The only problem with that is I don't think my computer (Surface Go OG edition) will be able to connect to any projector, so I'm still thinking about what to do about that. Alternatively I could do slides and participants could watch and ask questions or code along if they like.

Other than that a little bit of follow-up on what you can do with your own server (backing up files, SOCKS proxy, etc...) as well as your own domain name (custom email addresses) if you choose to purchase them could be useful too I think.

**Comment by nth10sd** [comment]
@andymckay Any thoughts?

**Comment by andymckay** [comment]
Thanks for the ping @nth10sd 

Sounds good @kburts, thank you. I think a how to use Pelican would be a great introductory talk for many. 

I'm not sure about your Surface, but I do know at the Jane office there are lots of dongles - what are the ports on that machine? I do have Macbooks I could lend you, but I know what its like trying to demo on an unfamilar machine.

Would end of Feb or early March work for you?

**Comment by kburts** [comment]
So the Mighty Surface Go has a single USB-C port which I tried to use for a movie night and it doesn't work connecting to monitors, it also has it's own special surface connector which I've never used. I think actually I'd just have all the slides hosted on Google Docs and could borrow a laptop but would not install or log into anything. With that people could either follow along with their own computers or if they've done enough coding for the day hopefully the talk would be entertaining and informative enough that they'd still get something out of it :).

For timing end of Feb after work on a weekday works really well for me! Early march I'm trying to schedule a bit open to plan a ski traverse and am waiting to see how conditions and stuff are looking

**Comment by andymckay** [comment]
Fair enough, thanks Microsoft. I'll have a MacBook ready for you as well and we can figure which works best.

How about Wednesday 28th Feb at Jane HQ (500 - 138 13th Street East, North Vancouver
British Columbia, Canada V7L 0E5), at about 6:30pm?

**Comment by kburts** [comment]
That would be perfect for me, thanks a lot 🌞 

I'll post my slides here when I've got em put together (probably next weekend) just in case you or anyone else from the group wants to check them out, but I don't think that's necessary at all.

**Comment by nth10sd** [comment]
@andymckay unfortunately I won't be available on Feb 28, Wed, to help out.

**Comment by kburts** [comment]
Alrighty I've got the slides started here https://docs.google.com/presentation/d/12Ob1Kxw8ifirwQSlBQjHge70aQLXykLdF_0WWcRnDDY/edit?usp=sharing and I'd say I'm pretty well ready to go for Wednesday 🌞 

Just a heads up but the Meetup event says location TBD, but should probably be changed to the Jane office!

**Comment by andymckay** [comment]
Great, thanks updated location.
