### ISSUE TITLE
Important notice: ending of Meetup account.

### ISSUE THREAD

**Issue by andymckay** [vancouver/vanpy#25]
Due to an increase in Meetup pricing to over $700 CAD a year, we are getting off of Meetup. Details are here: https://mckay.pub/2024-06-12-leaving-meetup/

Things we need to do:
* [x] Post a blog about why. See https://mckay.pub/2024-06-12-leaving-meetup/
* [x] Post a discussion on Python and Django meetups
* [x] Put it on Mastodon
* [x] Enable discussion on GitHub
* [x] Update the `readme` to encourage people to remember to `Watch` and follow `All Activity`  
* [x] Grab a copy of the member list, not sure why but may as well for a bit.
* [x] Actually cancel the subscription.

Anything else?

**Comment by andymckay** [comment]
What's confusing @galenseilis?

**Comment by galenseilis** [comment]
@andymckay No confusion. I had not realized I had put an emoji on the post.

**Comment by andymckay** [comment]
Oh ok, that's cool 😆

**Comment by andymckay** [comment]
Done, the next billing cycle is July 7th and I'll no longer be organizer of the Meetups then.
