### ISSUE TITLE
Meeting: September 9th Round Table

### ISSUE THREAD

**Issue by andymckay** [vancouver/vanpy#28]
We've got a new meeting coming up 🎉😎

## When: 

Monday September 9th at 6:30pm

## Where: 

At OXD offices in Gastown see issue #27 for more details 

## Talks: 

We don't have a specific talk, but are doing a round table chat with the subject "what I learnt over the summer" 😀

See the [readme for info on our talk types](https://github.com/vancouver/vanpy/blob/master/README.md)

## Standard info
* Everyone who comes should follow the [code of conduct](https://github.com/vancouver/vanpy/blob/master/code_of_conduct.md), which we will enforce. Be nice to each other and make a space we can all visit.
* We'll try to make every meeting a hybrid one, so people can can join remotely. We do understand that not everyone is comfortable turning up to a room full of people.
* If there is a room limit, we'll come up with a system to figure that out.
* Recording the meeting isn't something we plan on doing just yet.
* We encourage speakers to share their slides and demos later on if possible, but its up to the speakers.

That's it, we hope you can join us and come hang out with fellow Python people.

**Comment by tavallaie** [comment]
I randomly find you and why you leave meetup, I have a nerdy idea for how you can manage signup system, 
make a python code for validation of yaml file. 
that yaml file should has capacity option, and for people who can join you they add their github user name on the yaml and make a pull request :) 
you can manage that by accepting their PR.

**Comment by andymckay** [comment]
Thanks for the suggestion @tavallaie. We totally could do something like that. At this point I don't really feel a need to have a sign up system, unless we start to reach the limit of what a venue can hold. That's not a problem we've had yet, but it we will hopefully get more and more people coming.

**Comment by tavallaie** [comment]
Unfortunately, currently, I am stocked in Iran, but I share your meetup with my fellow Iranians in Vancouver.

**Comment by Goulustis** [comment]
Is there a signup link somewhere?

**Comment by andymckay** [comment]
> Is there a signup/link somewhere?

No signup is needed, we haven't hit room limits so needed a sign up process yet. So just come on by 😀

**Comment by freedryk** [comment]
Where will the link for the hybrid meeting be posted?

**Comment by andymckay** [comment]
If we can get it working, look out for a link here 😁

**Comment by orcsly** [comment]
Here is the Zoom link for the remote session:

https://oxdtf.zoom.us/j/83433284881?pwd=ZOEphaNH5XWuuUp1PlU6TqVgbmWlIR.1

**Comment by trentm** [comment]
I am at the front door at street level … and late

**Comment by freedryk** [comment]
Duckdb: https://duckdb.org/
pyarrow: https://arrow.apache.org/docs/index.html

**Comment by freedryk** [comment]
uv: https://github.com/astral-sh/uv

**Comment by freedryk** [comment]
mypy: https://www.mypy-lang.org/
pyright: https://github.com/microsoft/pyright
django-stubs: https://github.com/typeddjango/django-stubs

**Comment by andymckay** [comment]
Visidata: https://www.visidata.org/

**Comment by andymckay** [comment]
Snakemake: https://snakemake.readthedocs.io/en/stable/

**Comment by andymckay** [comment]
Django oauth toolkit: https://mariatta.ca/posts/extending-dj-oauth-toolkit-model/

**Comment by Mariatta** [comment]
Proposal to adopt the CalVer versioning for Python https://peps.python.org/pep-2026/
