### ISSUE TITLE
Meeting: September Thursday 14th, 7pm

### ISSUE THREAD

**Issue by andymckay** [vancouver/vanpy#3]
We'd like to get a new meeting coming up 🎉😎

## When

Thursday 14th, 7pm PT

## Where

Let's just go on zoom for the first one and get things organized there.

* https://zoom.us/j/98547434487?pwd=eWZuVkcvbi8wSHJYN2NkdnZWNTRydz09
* Meeting ID: 985 4743 4487
* Passcode: 2NuvpS

## Agenda

* Say hi to each other.
* Do we have enough people to get this group going?
* Fold in the Django user group?
* Does anyone know of any space?
* Can we get some talks on the agenda?
* Ditching meetup.
* Anything else

## Standard info
* Everyone who comes should follow the [code of conduct](https://github.com/vancouver/vanpy/blob/master/code_of_conduct.md), which we will enforce. Be nice to each other and make a space we can all visit.
* We'll try to make every meeting a hybrid one, so people can can join remotely. We do understand that not everyone is comfortable turning up to a room full of people.
* If there is a room limit, we'll come up with a system to figure that out.
* Recording the meeting isn't something we plan on doing just yet.
* We encourage speakers to share their slides and demos later on if possible, but its up to the speakers.

That's it, we hope you can join us and come hang out with fellow Python people.

**Comment by andymckay** [comment]
https://zoom.us/j/97753835473?pwd=WjMzYnhSb0s2YmRKM2VqOG5HbkJlQT09

**Comment by andymckay** [comment]
Thank you everyone for coming, it was so good to see you all. Here's my notes, but I spent too long talking. Please feel to add in your notes into the issue.

**Present:** Andy, Bryan, Kevin, Kevin (the other Kevin), Carson, Aaron, Rob, Paulo, Indika, Ada, Andrés, Romilson, Ivan. Unfortunately we then ran out of time in zoom and had to jump into another zoom and lost a couple of people 😭 

Bryan shared some history: Django user group started in 2008. Then Bryan and Andy joined forces together with the Python group. Was so great to meet so many people. The groups went from being small and personal, from casual, to "organize a wedding every week" - we need a venue, sponsors etc. Went from something that was a fun thing on the side to a something less fun.

* Do we have enough people to get this group going?

Based on the fact that 13 people turned up to a Zoom meeting and the amount of interest, probably. 👍🏾 

* Fold in the Django user group?

Django is still going strong, but the group has languished. Over the years we've seen interests in particular areas grow and shrink (for example LLM is hot in Python now). As long as one subject doesn't take over it's fine. If it grows too big and there is an organizer, we could move that off into a new group.

* Does anyone know of any space?

Andy: has a backup space, that he's working on in North Vancouver. But that's a bit hard for most people.
Bars or restaurants are ok, but hard to be inclusive and very noisy. Ok to go after a talk there.
If we chat to recruiters, they can often help us get space from sponsoring companies
Recruiters - we've had a couple of bad experiences in the past, we just need to set the line.

Kevin: Betaworks might be an option.
For sponsors, who provide space, we should be clear what they get out of it.
Key point for a location: Skytrain closeness is important for most people.

* Can we get some talks on the agenda?

We should be open and inclusive and encourage a diversity of talkers and subject. Encourage all levels to give a talk. Teaching a  is a good way of learning. All topics are very welcome. Default to being in-person, we could do a remote talker, but that should be an exception.

Do we have a YouTube channel? Nope. Could possibly do, but recording sound, video, slides etc well is hard.

Speakerlight (sp?) a way of voting on talks, as lightning talks. Will be nice when we get lots of talks.

Other good ways to get people:

Universities are a good way to pull people in.
Colleagues at companies.

* Ditching meetup.

GitHub seems ok 👍🏾 
Mastodon 👍🏾 
Slack or Discord - sounded like a good idea.

Should we have a website? Between Bryan and I think we've set up multiple websites. Then a few years they break and fall over. Even then you've got to work to get ranking these days so maybe? 🤙🏾 

We should find someone we trust to take over Meetup, if we can. That will retain some discoverability.

---

That's it. My goal is to get a meet up for October. So we've got to:
* Find a venue
* Find a talker, or you'll all be unfortunate enough to hear me talk.

If you find anyone, please add in an issue to this repo.

Thanks everyone!

**Comment by phsantosjr** [comment]
Hi Andy, thanks for the information.
Just one point, it is Speaker Fight not SpeakerLight. The website is that: https://speakerfight.com/events/
